window.__POSUDAMART_RUNTIME_CONFIG__ = Object.freeze({
  supabaseUrl: 'https://nazycxjgvaefcglfvykk.supabase.co',
  supabaseAnonKey: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5henljeGpndmFlZmNnbGZ2eWtrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ3MjEyNTYsImV4cCI6MjA5MDI5NzI1Nn0.to1CrdAEwSzJlP4OFoqhEbFtE_nkZQv6_Lpojcr5laE',
});
